### DISCUSSION TITLE
adds the possibility to change the location of the servers

### DISCUSSION THREAD

**Discussion by tobfd** [pelican-dev/panel#928] [Ideas]
I have a vps server with 20gb disk space with the operating system and then I have a 250gb hard disk mounted and I want the servers and the backups to be stored on the 250gb hard disk. I have already edited the configuration file at system: data: mnt/250gb hard disk mount path so that the servers are stored there. But you can set it up so that when you create a node it asks you for a path where you want to store your servers and backups and stuff. And in the health tab under used disk space i only see the small hard drive and not the hard drive where my servers are stored.

**Comment by rmartinoscar** [comment]
Hey you can change that in the config.yml
```yaml
system:
  root_directory: /var/lib/pelican
  log_directory: /var/log/pelican
  data: /var/lib/pelican/volumes
  archive_directory: /var/lib/pelican/archives
  backup_directory: /var/lib/pelican/backups
```

Either change those or create a bind mount so it mounts /mnt/250gb under /var/lib/pelican so you keep the same path


>I made an issue on https://github.com/pelican-dev/wings/issues/63
