### DISCUSSION TITLE
Issues with a docker compose installation

### DISCUSSION THREAD

**Discussion by SirEndii** [pelican-dev/panel#967] [General]
Disclaimer: I know that docker is not fully supported yet. I just hope that one of the collaborators or a community member can help me here.

Greetings,
we currently try to switch from pterodactyl to pelican, and we are looking forward to a full kubernetes/docker support in the future.
Just for now, I tried to install the panel on my host using compose. I cloned the repo, configured the compose.yml and tried to run it using `docker compose up`

But it just seems to freeze at the end?
```
[+] Running 3/3
 ✔ Volume "pelican_pelican-data"  Created                                                                                                                                                                                                                                                                               0.0s 
 ✔ Volume "pelican_pelican-logs"  Created                                                                                                                                                                                                                                                                               0.0s 
 ✔ Container pelican-panel-1      Created                                                                                                                                                                                                                                                                               0.1s 
Attaching to panel-1
panel-1  | external vars don't exist.
panel-1  | Generating key.
panel-1  | Generated app key: 9xQVg7n71hduSGaoiX2Io6KeDkuwvVZt # I know this is sensible data - but I will regenerate it later
panel-1  | APP_KEY is already set.
panel-1  | Migrating Database
panel-1  | 
panel-1  |    INFO  Preparing database.  
panel-1  | 
panel-1  |   Creating migration table ...................................... 14.60ms DONE
panel-1  | 
panel-1  |    INFO  Running migrations.  
panel-1  | 
panel-1  |   2016_01_23_195641_add_allocations_table ....................... 12.38ms DONE
panel-1  |   2016_01_23_195851_add_api_keys ................................ 11.84ms DONE
...
panel-1  |   2025_01_09_143607_database_host_node_foreign_delete_cascade ... 40.56ms DONE
panel-1  | 
panel-1  | Optimizing Filament
panel-1  | 
panel-1  |    INFO  Caching components and Blade icons.  
panel-1  | 
panel-1  |   Caching components ............................................. 0.71ms DONE
panel-1  |   Caching Blade icons .......................................... 164.87ms DONE
panel-1  | 
panel-1  | Starting PHP-FPM only
panel-1  | Starting Supervisord
Gracefully stopping... (press Ctrl+C again to force)
```

I waited about 30 minutes but no luck. I am not sure if this is just not working yet or if I configured something wrong.
I disabled caddy since we use our nginx proxy.

```yml
  GNU nano 7.2                                                                                                                                                                             compose.yml *                                                                                                                                                                                     
x-common:
  panel:
    &panel-environment
    APP_URL: "https://pelican.intelligence-modding.de" # can be set to 'http://localhost' on port 80 only
    ADMIN_EMAIL: "info@denizdemiroglu.de"

    APP_DEBUG: "true"
    APP_ENV: "production"

  mail:
    &mail-environment
    MAIL_DRIVER: "log"
    # MAIL_HOST: ""
    # MAIL_PORT: ""
    # MAIL_FROM: ""
    # MAIL_USERNAME: ""
    # MAIL_PASSWORD: ""
    # MAIL_ENCRYPTION: ""

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#

services:
  panel:
    image: ghcr.io/pelican-dev/panel:latest
    build: .
    restart: always
    networks:
      - default
    ports:
#      - "80:80"
#      - "443:443"
       - "9001:9000" # enable when not using caddy to be abel to reach php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway" # shows the panel on te internal docker network as well. usually '172.17.0.1'
    volumes:
      - pelican-data:/pelican-data
      - pelican-logs:/var/www/html/storage/logs
    environment:
      <<: [*panel-environment, *mail-environment]
      XDG_DATA_HOME: /pelican-data
      SKIP_CADDY: true # enable when not using caddy.

volumes:
  pelican-data:
  pelican-logs:

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
```

And I have another question. How could I set up things like mysql? Are there any env variables for that or is there maybe a list for all env variables?
Usually we do that using `php artisan p:environment:database` but that does not really work in my case

I also have my nginx file here if someone needs it/sees something wrong
```conf
server {
    client_max_body_size 0;
    server_name pelican.intelligence-modding.de;
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://127.0.0.1:9001/;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/pelican.intelligence-modding.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pelican.intelligence-modding.de/privkey.pem;
}

server {
    if ($host = pelican.intelligence-modding.de) {
        return 301 https://$host$request_uri;
    }

    server_name pelican.intelligence-modding.de;
    listen 80;
    return 404;
}
```

It would be sweet if anyone could help!
